### ISSUE TITLE
Trying to understand how to use.

### ISSUE THREAD

**Issue by funcJeff** [serejahh/UnboxedAlamofire#13]
I'm a very new to writing (proper modern decent) clients to web APIs. I am trying to figure out what UnboxedAlamofire gets me if I'm already using AF's `responseJSON` method. Installing and playing around today, this is what I have with only AF and Unbox.

```Swift
Alamofire.request("https://myapi.lol/candy"
            , method: .post
            , parameters: someParameters
            , encoding: JSONEncoding.default).responseJSON { response in
                guard let json = response.result.value as? Dictionary<String, String> else {
                    assertionFailure("No data?")
                    return
                }
                do {
                    let result: CandyResult = try unbox(dictionary: json)
                    doSomethingWith(result)
                } catch {
                    print("An error occured: \(error)")
                }
        }
```

Thanks.

**Comment by Coolone3000** [comment]
@funcJeff 

UnboxedAlamofire would let you unbox the response without any extra work. You'll notice that all you do is specify the object to be unboxed to and UnboxedAlamofire will parse out the JSON and unbox for you to your given type. It makes the code extremely clean. Hope this explanation helps. Take care!

```swift
    request("https://myapi.lol/candy",
                method: .post,
                parameters: someParameters,
                encoding: JSONEncoding.default).responseObject { (response:DataResponse<CandyResult>) in
            guard let candyResult = response.result.value else {
                print(response.result.error)
                return
            }
            
            doSomethingWith(candyResult)
        }
```

**Comment by funcJeff** [comment]
When I try that I get compiler build error:

```
Value of type 'DataRequest' has no member 'responseObject'.
```

So I look at AF docs for "responseObject", and I find [section "Generic Response Object Serialization"](https://github.com/Alamofire/Alamofire#custom-response-serialization). In there it looks like I have to extend `DataResponse` myself to create a `responseObject` method. And then I would have to make `Candy` conform to `ResponseObjectSerializable`, right?

I'm using these versions:
```
github "Alamofire/Alamofire" "4.1.0"
github "johnsundell/unbox" "2.2.1"
github "serejahh/UnboxedAlamofire" "2.0.1"
```

**Comment by funcJeff** [comment]
Doh! It is the `responseObject` method which _UnboxedAlamofire_ is providing! I was simply not importing it in the file! Oh the embarrassment...
