### ISSUE TITLE
iOS deployment target 8.0

### ISSUE THREAD

**Issue by tarigancana** [serejahh/UnboxedAlamofire#14]
I check on Alamofire and Unbox that both of this pods still using 8.0 as deployment target.
Can we use the same deployment target ? or there any reason why need to change to 9.0?

**Comment by serejahh** [comment]
The reason is Alamofire 4.0 [had only iOS 9 support](https://github.com/Alamofire/Alamofire/tree/4.0.0). It seems they support iOS 8 now so I gonna add iOS 8 support too
