### ISSUE TITLE
allowInvalidElements in serializeUnboxArrayResponse

### ISSUE THREAD

**Issue by dalu93** [serejahh/UnboxedAlamofire#18]
Hi,
Is there a possibility you can allow the `allowInvalidElements` parameter in the API to get anyway an array response, even if one or more elements are not parsable? Thanks
More info here: https://github.com/JohnSundell/Unbox/pull/41

**Comment by serejahh** [comment]
Hi @dalu93. Thanks for using the library. Just merged the PR, will be available soon in a new release

**Comment by zdenektopic** [comment]
Any updates on that release?

**Comment by serejahh** [comment]
@zdenektopic 2.0.4 is live 👍 
Sorry for such delay

**Comment by zdenektopic** [comment]
I am unable to make it work with carthage :/

**Comment by serejahh** [comment]
What's the problem?
