### ISSUE TITLE
Support for Unbox 4.0.0

### ISSUE THREAD

**Issue by Ohems** [serejahh/UnboxedAlamofire#23]
The Unbox library has progressed to [version 4.0.0](https://github.com/JohnSundell/Unbox/releases/tag/4.0.0) with Swift 5 support. Any chances for this package to follow?

**Comment by serejahh** [comment]
Hey @Ohems. Unbox has been deprecated so I mark the project deprecated as well. I hope you had a great time with UnboxedAlamofire 😀
