### ISSUE TITLE
Swift3 ?

### ISSUE THREAD

**Issue by arsonik** [serejahh/UnboxedAlamofire#4]
Any plan on making a swift3 branch ?

**Comment by serejahh** [comment]
Hi @arsonik! Sure, I'm gonna add swift3 branch on the week. Stay tuned 😉

**Comment by serejahh** [comment]
Hi @arsonik , @clayellis, @markiv. Sorry for the long update: https://github.com/serejahh/UnboxedAlamofire/pull/7

**Comment by serejahh** [comment]
Unfortunately, I can't push a new podspec due to `Unbox` doesn't have a podspec with Swift 3. Once https://github.com/JohnSundell/Unbox/issues/119 is closed, I'll push the podspec
