### ISSUE TITLE
Alamofire 4.0 ?

### ISSUE THREAD

**Issue by gbanfalvisk** [serejahh/UnboxedAlamofire#5]
Supposedly there's quite a few breaking changes, but it seems quite a bit nicer.

**Comment by serejahh** [comment]
Hi @gbanfalvisk! 

Sure, I'll merge it to `master` soon. Now you can check https://github.com/serejahh/UnboxedAlamofire/pull/7

**Comment by serejahh** [comment]
Now it's available. Please, update to `2.0`
