### ISSUE TITLE
Error building framework usingCarthage

### ISSUE THREAD

**Issue by buppal** [serejahh/UnboxedAlamofire#8]
I am upgrading to Swift 3.0. Whenever I build using carthage, I get this error:

*\* BUILD FAILED **

The following build commands failed:
    CompileSwift normal x86_64 /Users/buppal/Desktop/brelp-ios/Carthage/Checkouts/UnboxedAlamofire/UnboxedAlamofire/UnboxedAlamofire.swift
    CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
/Users/buppal/Desktop/brelp-ios/Carthage/Checkouts/UnboxedAlamofire/UnboxedAlamofire/UnboxedAlamofire.swift:10:8: error: module file was created for incompatible target x86_64-apple-ios9.0: /Users/buppal/Desktop/brelp-ios/Carthage/Checkouts/UnboxedAlamofire/Carthage/Build/iOS/Alamofire.framework/Modules/Alamofire.swiftmodule/x86_64.swiftmodule
A shell task (/usr/bin/xcrun xcodebuild -project /Users/buppal/Desktop/brelp-ios/Carthage/Checkouts/UnboxedAlamofire/UnboxedAlamofire.xcodeproj -scheme UnboxedAlamofire-macOS -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
*\* BUILD FAILED **

The following build commands failed:
    CompileSwift normal x86_64 /Users/buppal/Desktop/brelp-ios/Carthage/Checkouts/UnboxedAlamofire/UnboxedAlamofire/UnboxedAlamofire.swift
    CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

I have successfully upgraded Alamofire and AlamofireImage to the Swift 3.0 compatible version without any issues.

**Comment by serejahh** [comment]
Hi @buppal! Does it happen when you run `carthage update`? Did you update to `2.0`?
