### ISSUE TITLE
Compile Error 'invalidData' is inaccessible due to 'fileprivate' protection level

### ISSUE THREAD

**Issue by stefantheissen** [serejahh/UnboxedAlamofire#9]
Hi, if i try to use your code i get the following compilation error

 'invalidData' is inaccessible due to 'fileprivate' protection level

I am using Xcode 10, Swift 3.

**Comment by serejahh** [comment]
Hi @stefantheissen, @sergii-frost. Thanks for reporting the issue. It'll be fixed in `2.0.1`, PR is reade

**Comment by sergii-frost** [comment]
@serejahh thanks for the fix!
